# Generated by Django 3.1.12 on 2021-08-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('a', 'Accessories'), ('b', 'Homeware'), ('c', 'Electronics'), ('d', 'Garden'), ('e', 'Kitchen'), ('f', 'Miscellaneous')], default='Miscellaneous', max_length=1),
        ),
    ]
