# Generated by Django 3.1.12 on 2021-08-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210820_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('a', 'Accessories'), ('b', 'Homeware'), ('c', 'Electronics'), ('d', 'Gardenware'), ('e', 'Kitchenware'), ('f', 'Miscellaneous')], default='Miscellaneous', max_length=1),
        ),
    ]
